version: "3.7"

services:
  jt-slackbot-core:
    build:
      context: ./core
      dockerfile: Dockerfile.dev
    container_name: jt-slackbot-core
    depends_on:
      - jt-slackbot-dialog
    volumes:
      - ./core/logs:/var/log/jt-slackbot-core
    network_mode: host

  jt-slackbot-dialog:
    build:
      context: ./dialog
      dockerfile: Dockerfile.dev
    container_name: jt-slackbot-dialog
    volumes:
    - ./dialog/data:/app/data
    ports:
    - "5000:5000"
    network_mode: host
