version: "3.7"

services:
  jt-slackbot-core:
    build:
      context: ./core
      dockerfile: Dockerfile.dev
    container_name: jt-slackbot-core
    depends_on:
      - jt-slackbot-dialog
    volumes:
      - ./core/src:/app
      - ./core/logs:/var/log/jt-slackbot-core
    network_mode: host

  jt-slackbot-dialog:
    build:
      context: ./dialog
      dockerfile: Dockerfile.dev
    container_name: jt-slackbot-dialog
    depends_on:
      - jt-slackbot-dialog-db
    environment:
      - DEBUG_SERVER=true
    volumes:
      - ./dialog/src:/app
    ports:
      - "5000:5000"
    network_mode: host

  jt-slackbot-dialog-db:
    image: mysql:5.7.22
    container_name: jt-slackbot-dialog-db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=dialog_history
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_ROOT_PASSWORD=
    network_mode: host